apiVersion: v1
kind: Service
metadata:
  name: product-service-nodeport
  labels:
    app: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      nodePort: 30281
      protocol: TCP